### ISSUE TITLE
fatal error when running a certain workflow (foreground service)

### ISSUE THREAD

**Issue by ctwhome** [ctwhome/SmartPlay#3]
```
FATAL EXCEPTION: main (Ask Gemini)
Process: com.example.smartplay, PID: 13319
android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{7694dbb u0 com.example.smartplay/.workflow.notifications.NotificationService}
at android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:2025)
at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:1996)
at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException(Unknown Source:0)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2261)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at android.app.ActivityThread.main(ActivityThread.java:7962)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)
Caused by: android.app.StackTrace: Last startServiceCommon() call for this service was made here
at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1920)
at android.app.ContextImpl.startForegroundService(ContextImpl.java:1875)
at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:827)
at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:827)
at androidx.core.content.ContextCompat$Api26Impl.startForegroundService(ContextCompat.java:931)
at androidx.core.content.ContextCompat.startForegroundService(ContextCompat.java:703)
at com.example.smartplay.workflow.WorkflowManager.<init>(WorkflowManager.kt:33)
at com.example.smartplay.RecordingActivity.initializeManagers(RecordingActivity.kt:190)
at com.example.smartplay.RecordingActivity.onCreate(RecordingActivity.kt:87)
at android.app.Activity.performCreate(Activity.java:8360)
at android.app.Activity.performCreate(Activity.java:8339)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1384)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3676)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3832)
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2327)
at android.os.Handler.dispatchMessage(Handler.java:106) 
at android.os.Looper.loopOnce(Looper.java:201) 
at android.os.Looper.loop(Looper.java:288) 
at android.app.ActivityThread.main(ActivityThread.java:7962) 
at java.lang.reflect.Method.invoke(Native Method) 
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952) 
```

workflows:
```json
[
  {
    "workflow_name": "CHAR TEST",
    "questions": [
      {
        "question_id": 1,
        "question_title": "How do you feel right now?",
        "answers": [
          "👍",
          "🤢",
          "🤷‍♀️"
        ],
        "time_after_start": 600,
        "frequency": 3,
        "time_between_repetitions": 600
      },
      {
        "question_id": 2,
        "question_title": "Energy level?",
        "answers": [
          "🔋",
          "🪫"
        ],
        "time_after_start": 900,
        "frequency": 2,
        "time_between_repetitions": 600
      },
      {
        "question_id": 3,
        "question_title": "Any stress?",
        "answers": [
          "😭",
          "🥳"
        ],
        "time_after_start": 2100,
        "frequency": 1
      },
      {
        "question_id": 4,
        "question_title": "Feeling motivated?",
        "answers": [
          "Niet",
          "Een Beetje",
          "Zeker"
        ],
        "time_after_start": 2400,
        "frequency": 1
      }
    ]
  }
]
```

**Comment by ctwhome** [comment]
I've fixed the ForegroundServiceDidNotStartInTimeException by properly implementing foreground service requirements in NotificationService.kt. The service now:

- Starts in foreground mode immediately when created
- Maintains all existing notification functionality for questions
- Properly cleans up when destroyed

The error should no longer occur when the service is started. The app will show a persistent "Recording session in progress" notification while running, as required for foreground services.
